---
# www.yml: Playbook para servidores web
- hosts: db
  sudo: yes
  pre_tasks:
     - shell: echo 'I":" Iniciando configuracion..'
  roles:
     - base
     - ansible-role-redis-master
  vars_files:
     - vars/main.yml
  post_tasks:
     - shell: echo 'I":" Finalizando configuracion..'
